### ISSUE TITLE
Request to remove toybox[.]com

### ISSUE THREAD

**Issue by ChuckFrey** [columndeeply/hosts#1]
Greetings from afar friend. Not knowing why a 3D printing site was included I wanted to check in w/ you to see if `toybox.com` can be removed from [hosts01](https://raw.githubusercontent.com/columndeeply/hosts/main/hosts01).

When looking through the file for the word `toybox` I can see why other sites should be included. I am not sure that this one should be.

Thank you for your consideration.

**Comment by columndeeply** [comment]
Absolutely, I've checked the domain and it shouldn't be blocked at all. I've added it to the whitelist. Thanks for opening the issue!

It came from [this](https://github.com/zangadoprojets/pi-hole-blocklist/blob/main/Pornpages.txt) list. I'll open an issue to get it whitelisted on their side too.
