### ISSUE TITLE
Split url redirect and sites users might whitelist into another file

### ISSUE THREAD

**Issue by Macaquinyo** [columndeeply/hosts#12]
I'm using the list with pihole.

If you import the whole list into pihole, sites like google or youtube will be blocked. Pihole seems to blacklist any url in the file, instead of redirecting to the specified ip. 

I suggest spliting this lines (v.gr. 216.239.38.120 google.com) into another file so that users don't have to deal with whitelisting this ips on pihole.

Also, users might want to whitelist mainsteam sites like reddit or facebook. Not many text editors can edit a 90mb file, let alone a 350mb one. So, I suggest splitting those lines into a separate file also.

**Comment by Macaquinyo** [comment]
A prototype of this file [prototype_list.txt](https://github.com/user-attachments/files/17185941/prototype_list.txt)

**Comment by columndeeply** [comment]
Sounds good. I had no idea pihole ignored the IPs and just blocked all URLs...

I'll try to have it done by tomorrow's 2024.10.01 release
