### ISSUE TITLE
Sites to remove

### ISSUE THREAD

**Issue by Macaquinyo** [columndeeply/hosts#13]
As I said in issue #10, I made the intersection of your list with a top 10000 domains list.
Well, I manually checked EVERY domain of the intersection, and this domains are in your list and should not be. I was pretty strict, so I don't think you'll find any problem with the list.

Upstream lists are pretty... well. They block a site about Essex, and a site about Tottenham Hotspurs. I guess it's because esSEX and HOTspurs. Pretty bad.
[to_remove.txt](https://github.com/user-attachments/files/17185868/to_remove.txt)

**Comment by Macaquinyo** [comment]
This list contains urls that either serve ads, or are trackers. I don't know if this ads could be pornographic, but I don't think so (after all, I checked with another 2 porn blocking lists and they were not there) Maybe getting this sites off the list could help with normal internet navigation? The list is good to have anyway, more information about what's on your list.
[ads_and_trackers.txt](https://github.com/user-attachments/files/17185855/ads_and_trackers.txt)

**Comment by Macaquinyo** [comment]
I'll let here this usefull bash comand. Given file1 and file2, it generates file3 that contains every line of file2 that is not present also in file1. [= removes all lines present in file1 from file2]

awk '{if (f==1) { r[$0] } else if (! ($0 in r)) { print $0 } } ' f=1 file1 f=2 file2 > file3

**Comment by columndeeply** [comment]
Thanks for the list, I'll try to merge it before tomorrow's release. I'll remove the domains in the ads and tracker's list too.
