### ISSUE TITLE
[Adition Request]

### ISSUE THREAD

**Issue by Macaquinyo** [columndeeply/hosts#14]
Found in the wild

bombav.vip

p.s. ¿doesn't it make sense to leave this kind of issues open? You could add a label called "leave open" or something.

edit: remembered a nitter instance
xcancel.com

**Comment by columndeeply** [comment]
Thanks!

> p.s. ¿doesn't it make sense to leave this kind of issues open? You could add a label called "leave open" or something.
Yeah, you're right. I'll create two issues and pin them
