### ISSUE TITLE
Possible new sources?

### ISSUE THREAD

**Issue by joe820912boy** [columndeeply/hosts#2]
Like
https://abp.oisd.nl/
https://github.com/mhhakim/pihole-blocklist/blob/master/porn.txt

These two are also have many know porn list.
Maybe we could add them on list?

**Comment by joe820912boy** [comment]
And I would find more repo about the porn list

**Comment by columndeeply** [comment]
Hey! Thanks for opening this issue. mhhakim's list is already one of the sources. It's listed as "mhhakim's list #2".

The oisd.nl one is not a porn list. It looks like it has tracking, phishing and ad domains too. Looks like a general blocklist. I'm trying to keep the sources exclusively about porn.

If you find other porn focused lists feel free to send me a link and I'll add them to the sources.

**Comment by joe820912boy** [comment]
OK, thanks!

**Comment by joe820912boy** [comment]
Some domain LIKE format *.actonservice.com will be redirected to act-on.com.

And there should be classied to CNAME tracker, maybe needed remove from porn site list?

**Comment by columndeeply** [comment]
I'm not sure what you mean. Are you saying that *.actonservice.com are false positives and should be removed?

**Comment by joe820912boy** [comment]
Yes, you could confirm it again before you remove it

**Comment by columndeeply** [comment]
Sure, I've removed them from the list

**Comment by joe820912boy** [comment]
@columndeeply 

thank for updating lists!!

**Comment by joe820912boy** [comment]
@columndeeply 

some this format LIKE URI shouldn't be record in domain list 

in hosts01
https://eporner.com.es/
https://poop.vids.rip/
https://wargers.org/
https://www.ebookrenta.com/
https://www.pornbfvideo.com/
https://www.pussyboy.net/
https://www.pornv.xxx/
https://www.sexvid.pro/
https://www.xvideos51.com/

this should be transformed without "https://" prefix

**Comment by columndeeply** [comment]
@joe820912boy 

Thanks for letting me know! I didn't realize but the cleanup.sh script isn't removing the http(s) properly. I've opened a new issue for this (#3).

I'll try to get it fixed this weekend.
