### ISSUE TITLE
Fixing cleanup.sh to remove http(s) from the domains

### ISSUE THREAD

**Issue by columndeeply** [columndeeply/hosts#3]
The cleanup.sh script isn't removing http(s) from the urls (as mentioned in #2 by @joe820912boy).

For example, in hosts01:
https://eporner.com.es/
https://poop.vids.rip/
https://wargers.org/
https://www.ebookrenta.com/
https://www.pornbfvideo.com/
https://www.pussyboy.net/
https://www.pornv.xxx/
https://www.sexvid.pro/
https://www.xvideos51.com/

I'm also seeing a few that aren't just domains, for example:
iptorrents.com/torrents
lasmejoreswebsporno.com/en
lusthive.com/tym

These should have the "/tym", "/en", "/torrents", etc. The cleanup script should only keep the (sub)domain.

**Comment by joe820912boy** [comment]
Yes, 

there also exists that some url not domain, mainly in host02
LIKE reddit forum or twitter,

It exists some content about adult in it, but I have no idea it's suitable for DOMAIN

But maybe it works for host file used for blocking adult content

**Comment by columndeeply** [comment]
It should be fixed now. Let me know if you see anything else that should be changed.

**Comment by joe820912boy** [comment]
Ok sure, thanks for fix it

**Comment by joe820912boy** [comment]
@columndeeply 

"www.xnxx.com › search › x... "

in host03 needs be cleaned

**Comment by joe820912boy** [comment]
@columndeeply 

"www.newgrounds.com"
in host03,

"www.deusx.com"
in host02

seems they are game websit, not to be adult

**Comment by columndeeply** [comment]
Thanks for letting me know @joe820912boy. I've whitelisted deusx.com. NewGrounds is still banned because according to their rules they allow porn games/pictures. If anybody still wants to access the site they can whitelist it in their PiHole/AdGuard/whatever instance.

The "git.git.git" domains seem to be coming from a few sources, but the main one is: https://github.com/RPiList/specials/tree/master/Blocklisten

As far as I know it's still a valid domain so I would leave them listed.

Btw, if you find anything else could you open a new issue? Not sure why but GitHub isn't notifying me once an issue has been closed so I might miss your messages.

**Comment by joe820912boy** [comment]
OK, thanks

I will open new issue if find some invalid domain
